# Generated by Django 5.1.7 on 2025-04-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_public_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='public_submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
