# Generated by Django 5.1.7 on 2025-04-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_is_public_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='funding_needs',
            field=models.CharField(blank=True, choices=[('<10k', 'Less than $10,000'), ('10k-50k', '$10,000 - $50,000'), ('50k-100k', '$50,000 - $100,000'), ('100k-500k', '$100,000 - $500,000'), ('>500k', 'More than $500,000'), ('unknown', 'Not sure yet')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='project_stage',
            field=models.CharField(blank=True, choices=[('idea', 'Idea Stage'), ('prototype', 'Prototype/MVP'), ('operating', 'Operating Business'), ('scaling', 'Scaling Phase')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='tourism_focus',
            field=models.CharField(blank=True, choices=[('cultural', 'Cultural Tourism'), ('ecotourism', 'Ecotourism'), ('adventure', 'Adventure Tourism'), ('community', 'Community-Based Tourism'), ('digital', 'Digital Tourism Solutions'), ('gastronomy', 'Gastronomic Tourism'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('event', 'Tourism Event'), ('partner', 'Partner Organization'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('assessment', 'Under Assessment'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('incubation', 'In Incubation'), ('closed_won', 'Successful Project'), ('closed_lost', 'Not Proceeding')], default='new', max_length=50),
        ),
    ]
